server:
  port: 9090
# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
#    password: 123Aa!!!
    password: 123abc
    driver-class-name : com.mysql.cj.jdbc.Driver

    druid:
      filters: stat,wall  # 配置底层功能，sql监控和防火墙
      #      connectionInitSqls: set names utfm64
      #      <property name="connectionInitSqls" value="set names utf8mb4;" />
      #      aop-patterns: com.hhj.controller.* # 监控springbean

      # 详细配置stat
      filter:
        stat:
          slow-sql-millis: 1000 #定义一秒以上的为慢SQL
          db-type: mysql
          log-slow-sql: true # 记录慢SQL
        wall:
          config:
          #            drop-table-allow: false # 拦截所有删表方法
          db-type: mysql
          enabled: true #防止SQL注入问题

      #配置监控页面
      stat-view-servlet:
        enabled: true   # 开启监控页
        #        login-username: admin
        #        login-password: admin
      # 配置监控web
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      max-active: 2
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20


redis:
  host: 127.0.0.1
  port: 6379
  password: 123abc


#  type-aliases-package: com.hhj.seckill
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hhj.seckill.entry
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    com.hhj.seckill.mapper: debug # 设置指定包的日志级别（未指定的包按照root的日志级别执行）
    root: info  # 定义项目日志级别（默认是info）









