server:
  port: 9090
# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
#    password: 123Aa!!!
    password: 123abc
    driver-class-name : com.mysql.cj.jdbc.Driver

    druid:
      filters: stat,wall  # 配置底层功能，sql监控和防火墙
      #      connectionInitSqls: set names utfm64
      #      <property name="connectionInitSqls" value="set names utf8mb4;" />
      #      aop-patterns: com.hhj.controller.* # 监控springbean

      # 详细配置stat
      filter:
        stat:
          slow-sql-millis: 1000 #定义一秒以上的为慢SQL
          db-type: mysql
          log-slow-sql: true # 记录慢SQL
        wall:
          config:
          #            drop-table-allow: false # 拦截所有删表方法
          db-type: mysql
          enabled: true #防止SQL注入问题

      #配置监控页面
      stat-view-servlet:
        enabled: true   # 开启监控页
        #        login-username: admin
        #        login-password: admin
      # 配置监控web
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#      最大连接数
      max-active: 100
#      初始化连接池大小
      initial-size: 10
      max-wait: 60000
#      最小连接数
      min-idle: 10
#      间隔多久进行一次检测来关闭空闲的连接
      time-between-eviction-runs-millis: 4000
#      配置一个连接在连接池中最小生存时间
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      validation-query: "select 1"

  redis:
    host: 47.106.104.139
    port: 6379
    password: 123abc
    jedis:
      pool:
        max-active: 200
        max-idle: 50
        min-idle: 5
        max-wait: 1000
        time-between-eviction-runs: 30000

  rabbitmq:
    host: 47.106.104.139
    port: 5672
    virtual-host: /
    username: virtual
    password: virtual

    #    开启生产者消息确认
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        concurrency: 10
        prefetch: 100
        auto-startup: true
        default-requeue-rejected: true
        acknowledge-mode: manual
    template:
#      retry:
#        enabled: true
#        initial-interval: 1s
#        max-attempts: 3
#        max-interval: 10s
#        multiplier: 1.0
      mandatory: true





#redis:
#  host: 127.0.0.1
#  port: 6379
#  password: 123abc
#  lettuce:
#    max-active: 8
#    max-idle: 8
#    min-idle: 0
#    max-wait: -1ms


#  type-aliases-package: com.hhj.seckill
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hhj.seckill.entry
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    com.hhj.seckill.mapper: error # 设置指定包的日志级别（未指定的包按照root的日志级别执行）
    root: error  # 定义项目日志级别（默认是info）









